### ISSUE TITLE
Registration as provider not working

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-compass#111] opened 2023-08-23 10:24 UTC
### Describe the Bug
I get an http-500 when trying to register as a provider

### Steps to Reproduce
try to register from landing page

### Expected Behavior
Registration is done

**Comment by Docmale** [comment] 2023-09-12 08:09
see #127 for better description

**Comment by JoeyStk** [comment] 2023-09-13 09:49
Duplicate of #131

**Closed as completed by JoeyStk** 2023-09-13 09:49 UTC
Labels: bug, prio:high
